### ISSUE TITLE
Password visibility button

### ISSUE THREAD

**Issue by Devanshu1603** [dhairyagothi/StationGuide#238]
# ✨ Feature Request

### **Description of the Feature**
there must be password visibility off and on button.

### **Proposed Solution**
will add a password visibility toggle button.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by Devanshu1603** [comment]
@dhairyagothi  please assign me this issue under gssoc

**Comment by dhairyagothi** [comment]
already there bro

**Comment by dhairyagothi** [comment]
i think its not working correct it
