### ISSUE TITLE
Toggle sidebar issue

### ISSUE THREAD

**Issue by Devanshu1603** [dhairyagothi/StationGuide#239]
# 🐞 Bug Report

### **Describe the bug**
there must be a cross button when toggle sidebar is opened .

### **Expected behavior**
On clicking cross button sidebar must get closed.

### **Screenshots or Video**
![Screenshot 2024-10-14 003854](https://github.com/user-attachments/assets/d32ceaa3-80b6-4f5a-9718-316f60ec1fae)

@dhairyagothi  please assign me this issue under gssoc-extended , hacktober fest . will be happy to contribute.

**Comment by dhairyagothi** [comment]
check PR #208 
 merged now check and tell your issue
